In [1]:
#
import requests
import pandas as pd 
pd.set_option('display.max_rows', None)
from IPython.display import HTML

#
import mysql.connector
from mysql.connector import Error

#
import numpy as np

#
import os 
from dotenv import load_dotenv
load_dotenv()
password_sql = os.getenv("PASS_SQL")

#
import json

# EXTRACCIÓN DE DATOS EN DEEZER Y LAST.FM

In [2]:
# Función genérica para extraer las API 
def extraccion_API(endpoint, verbose=True):

    try:
        # Endpoint como argumento de función
        datos = requests.get(endpoint)
        if datos.status_code == 200:
            # Se permite print detallado
            if verbose: 
                print ("API conectada correctamente")
            # Se convierte datos a JSON para que sea manejable por el resto de funciones
            datos_json = datos.json()
            return datos_json
        else:
            # En caso de error, se imprime fallo 
            print (f"Error de conexión en API {endpoint}: {datos.status_code}")

    # Error de conexión        
    except requests.exceptions.ConnectionError as CnxE:
        print (CnxE)

    # Error de tiempo de espera
    except requests.exceptions.Timeout as TO:
        print (TO)
    
    # Cubrimos el resto de errores
    except requests.exceptions.RequestException as e:
        print (e)

In [3]:
# Lista los ID de los cantantes o grupos que se van a extraer
id_artistas = [12246, 160, 145, 564, 75491, 75798, 290, 483, 10803980, 1538640, 892, 10583405, 412, 13, 4050205, 384236, 119, 5620251, 259, 5962948, 196, 485, 425, 315929, 2446, 1755, 180, 98, 10977, 1434]

In [5]:
# Función para extraer los datos de artistas de Deezer
def extraer_artistas(id_artistas):

    # Se define lista vacía y el contador de verbose
    lista_artistas = []
    contador = 0
    # Se recorre un endpoint por artista
    for artistas in id_artistas:
        endpoint = f"https://api.deezer.com/artist/{artistas}"

        # Se lanza la función para extraer las API
        datos_artistas = extraccion_API(endpoint, verbose=False)
        contador += 1
        # Diccionario con los datos necesarios
        diccionario_artista = {
            "id_artista": datos_artistas["id"],
            "nombre": datos_artistas["name"]
            }
        lista_artistas.append(diccionario_artista)

    # Imprime el número de apis correctas
    print(f"{contador} APIs extraídas correctamente")
    # Unimos la lista de DF
    df_final = pd.DataFrame(lista_artistas)
    return df_final

In [6]:
df_artistas = extraer_artistas(id_artistas)
HTML(df_artistas.to_html(index=False))

30 APIs extraídas correctamente

In [7]:
# Función para extraer los datos de las canciones de Deezer
def extraer_canciones(id_artistas):

    # Lista vacía para el DF y contador
    lista_canciones = []
    contador = 0
    # Se recorre un endpoint por artista
    for artistas in id_artistas:
        endpoint = f"https://api.deezer.com/artist/{artistas}/top?limit=50"
        
        # Se lanza la función para extraer las API
        datos_canciones = extraccion_API(endpoint, verbose = False)
        contador += 1

        # Bucle para recoger los datos que necesitamos del JSON
        for cancion in datos_canciones["data"]:
            id_cancion = cancion["id"]
            id_artista = cancion["artist"]["id"]
            id_album = cancion["album"]["id"]
            titulo = cancion["title"]
            duracion = cancion["duration"]
            ranking = cancion["rank"]
            if len(cancion["contributors"]) == 1:
                colaboradores = False
            else:
                colaboradores = True

            # Diccionario creado con los datos extraidos del JSON
            diccionario_cancion = {
                    "id_cancion": id_cancion,
                    "id_artista": id_artista,
                    "id_album": id_album,
                    "title": titulo,
                    "duration": duracion,
                    "rank": ranking,
                    "contributors_bool": colaboradores
                }         
                        
            # Se añade el diccionario a la lista
            lista_canciones.append(diccionario_cancion)
    
    # Imprime el número de apis correctas
    print(f"{contador} APIs extraídas correctamente")        
    df_canciones = pd.DataFrame(lista_canciones)
    df_final = df_canciones.drop_duplicates(subset="id_cancion")
    return df_final, lista_canciones

In [8]:
df_canciones ,  lista_canciones = extraer_canciones(id_artistas) 
df_canciones.to_csv("listado_de_canciones.csv", index=False)

30 APIs extraídas correctamente

In [9]:
# Funcion para comprobar que los artistas elegidos tienen 50 canciones
def conteo_artistas(id_artistas):

    # Diccionario vacío para mostrar conteo
    diccionario_artistas = {}
    # Se recorren las APIs
    for artistas in id_artistas:
        endpoint = f"https://api.deezer.com/artist/{artistas}/top?limit=50"
        datos = extraccion_API(endpoint, verbose=False)
        
        # Enfrenta artistas con el número de canciones en la API
        diccionario_artistas[artistas] = len(datos["data"])
    return diccionario_artistas

In [10]:
diccionario_artistas = conteo_artistas(id_artistas)
diccionario_artistas

{12246: 50,
 160: 50,
 145: 50,
 564: 50,
 75491: 50,
 75798: 50,
 290: 50,
 483: 50,
 10803980: 50,
 1538640: 50,
 892: 50,
 10583405: 50,
 412: 50,
 13: 50,
 4050205: 50,
 384236: 50,
 119: 50,
 5620251: 50,
 259: 50,
 5962948: 50,
 196: 50,
 485: 50,
 425: 50,
 315929: 50,
 2446: 50,
 1755: 50,
 180: 50,
 98: 50,
 10977: 50,
 1434: 50}

In [11]:
# Función para extraer los géneros de Deezer
def extraer_genero():

    # Endpoint único
    endpoint = "https://api.deezer.com/genre/"
    try:
        datos_genero = extraccion_API(endpoint, verbose = True)
        df_genero = pd.DataFrame(datos_genero["data"])
        df_final = df_genero[["id","name"]]                       
        return df_final
    except:
        print ("error")

In [12]:
df_genero = extraer_genero()
HTML(df_genero.to_html(index=False))

API conectada correctamente

In [13]:
def extraer_album():
    album_ids_unicos = set()

    for cancion in lista_canciones:
        album_ids_unicos.add(cancion["id_album"])

    contador = 0
    lista_albumes = []
    for album_id in album_ids_unicos:
        endpoint = f"https://api.deezer.com/album/{album_id}"
        datos_albumes = extraccion_API(endpoint, verbose = False)
        contador += 1
        
        diccionario_albumes = {
            "id_album": datos_albumes["id"],
            "id_artista": datos_albumes["artist"]["id"],
            "id_genre": datos_albumes["genre_id"],
            "titulo": datos_albumes["title"],
            "n_canciones": datos_albumes["nb_tracks"],
            "fecha_lanzamiento": datos_albumes["release_date"]
        }     

        
        lista_albumes.append(diccionario_albumes)
    
    print(f"{contador} APIs extraídas correctamente") 
    df_final = pd.DataFrame(lista_albumes)
    return df_final

In [14]:
df_albumes = extraer_album()

603 APIs extraídas correctamente

In [15]:
def ajuste_genero():
    generos_faltantes = set(df_albumes["id_genre"]) - set(df_genero["id"])
    lista_generos_nuevos = []
    for genero in generos_faltantes:
        endpoint = f"https://api.deezer.com/genre/{genero}"
        generos_extraidos = extraccion_API(endpoint, verbose=True)
        if "error" in generos_extraidos:
            df_albumes.loc[df_albumes["id_genre"] == genero, "id_genre"] = 0
        else:    
            lista_generos_nuevos.append(generos_extraidos)
    
    if len(lista_generos_nuevos) > 0:
        df_final = pd.DataFrame(lista_generos_nuevos)[["id", "name"]]
        return df_final

In [16]:
df_albumes.to_csv("listado_de_albumes.csv", index=False)
df_ajuste_genero = ajuste_genero()
df_genero_final = pd.concat([df_genero, df_ajuste_genero], ignore_index=True)
HTML(df_genero_final.to_html(index=False))

API conectada correctamente
API conectada correctamente

In [17]:
def extraer_last_fm(df_artistas):

    lista_artistas = []
    contador = 0
    df_artistas["nombre"].str.replace(" ", "+")
    for nombre in df_artistas["nombre"]:
        endpoint = f"https://ws.audioscrobbler.com/2.0/?method=artist.getInfo&artist={nombre}&api_key=68eddfdc6b072ad56527a4199d979038&format=json"
        datos_last_fm = extraccion_API(endpoint, verbose=False)
        contador += 1
    
        diccionario_artistas = {
            "nombre" : datos_last_fm["artist"]["name"],
            "oyentes" : datos_last_fm["artist"]["stats"]["listeners"],
            "reproducciones" : datos_last_fm["artist"]["stats"]["playcount"],
            "biografia" : datos_last_fm["artist"]["bio"]["summary"]
        }
            
        
        lista_artistas.append(diccionario_artistas)

    df_final = pd.DataFrame(lista_artistas)
    df_final["biografia"] = df_final["biografia"].str.replace("\n", " ")
    print(f"{contador} APIs extraídas correctamente") 
    return df_final

In [18]:
df_artistas_fm = extraer_last_fm(df_artistas)
df_artistas_fm.to_csv("listado_de_artistas_fm.csv", index=False)

30 APIs extraídas correctamente

In [43]:
id_colaboradores = (set(df_albumes["id_artista"]) | set(df_canciones["id_artista"])) - set(id_artistas)
id_colaboradores

{11,
 230,
 359,
 413,
 556,
 1446,
 2896,
 3098,
 4088,
 4347,
 4474,
 4479,
 4962,
 5080,
 5828,
 7343,
 8631,
 9219,
 12178,
 75332,
 127322,
 165930,
 210977,
 246791,
 310260,
 380955,
 407188,
 554792,
 712271,
 1020109,
 1562681,
 1672366,
 3265001,
 3922661,
 3968561,
 4104927,
 4331004,
 4390053,
 4495513,
 4649104,
 4860761,
 4968870,
 5297021,
 5531258,
 5835993,
 5904266,
 6396188,
 6397900,
 7072729,
 7201102,
 7358224,
 7457468,
 7543848,
 7961888,
 8376040,
 8706544,
 9236850,
 9759672,
 9761322,
 9999412,
 11289472,
 12170972,
 12382106,
 12487862,
 58568762,
 67972932,
 79181242,
 98840272,
 108420982,
 141992442,
 207559207,
 213208547}

In [44]:
df_colaboradores = extraer_artistas(id_colaboradores)

72 APIs extraídas correctamente

In [45]:
df_colaboradores_fm = extraer_last_fm(df_colaboradores)

72 APIs extraídas correctamente

In [87]:
df_artistas["nombre"] = df_artistas["nombre"].str.lower()
df_artistas_fm["nombre"] = df_artistas_fm["nombre"].str.lower()
df_colaboradores["nombre"] = df_colaboradores["nombre"].str.lower()
df_colaboradores_fm["nombre"] = df_colaboradores_fm["nombre"].str.lower()
df_combinado_principales= pd.merge(df_artistas, df_artistas_fm, left_on="nombre", right_on="nombre")
df_combinado_colaboradores = pd.merge(df_colaboradores, df_colaboradores_fm, left_on="nombre", right_on="nombre")
df_combinado_artistas = pd.concat([df_combinado_principales, df_combinado_colaboradores], ignore_index=True)
df_combinado_artistas = df_combinado_artistas.drop_duplicates(subset="id_artista")
df_combinado_artistas

,id_artista,nombre,oyentes,reproducciones,biografia
0,12246,taylor swift,5989745,3716657384,Taylor Alison Swift is an American singer-song...
1,160,shakira,4939814,183414959,Shakira Isabel Mebarak Ripoll is a Colombian s...
2,145,beyoncé,6434581,708060557,Beyoncé Giselle Knowles-Carter (born Septembe...
3,564,rihanna,8359180,612131922,"Robyn Rihanna Fenty (born February 20, 1988), ..."
4,75491,lady gaga,7780825,1047223704,Stefani Joanne Angelina Germanotta (born 28 Ma...
5,75798,adele,5665588,321459407,"Adele Laurie Blue Adkins MBE (born May 5, 1988..."
6,290,madonna,5716862,372167910,"Madonna Louise Ciccone (born August 16, 1958) ..."
7,483,britney spears,6511637,501505752,"Britney Jean Spears (born December 2, 1981 in..."
8,10803980,blackpink,2032427,318339888,BLACKPINK (Hangul: 블랙핑크; Katakana :ブラックピンク; st...
9,1538640,little mix,1871879,114871114,Little Mix is a British girl group formed in 2...
10,892,coldplay,9163192,786245568,Coldplay is a British alternative rock and bri...
11,10583405,bad bunny,2629626,418256269,"Benito Antonio Martínez Ocasio (born March 10,..."
12,412,queen,7279341,430315365,Queen are a British rock band formed in London...
13,13,eminem,7841107,573808940,"Marshall Bruce Mathers III (born October 17, 1..."
14,4050205,the weeknd,5373837,1140740927,"Abel Makkonen Tesfaye, popularly known as The ..."
15,384236,ed sheeran,4257417,258702828,Edward Christopher Sheeran (born 17 February 1...
16,119,metallica,5222863,540150256,Metallica is an American heavy metal band form...
17,5620251,c. tangana,494943,29972574,"Antón Álvarez Alfaro (born July 16, 1990), kno..."
18,259,michael jackson,7005170,387015586,"Michael Joseph Jackson (August 29, 1958 - June..."
19,5962948,shawn mendes,2777694,144496218,Shawn Peter Raul Mendes is a Canadian singer. ...
20,196,the cranberries,4789159,161158367,The Cranberries were an Irish rock band formed...
21,485,garbage,2310575,74300838,Garbage is a Scottish and American alternative...
22,425,blondie,3481899,76018537,Blondie is an American rock band founded in Ne...
23,315929,pretenders,977156,10095950,Pretenders are a rock band who came to promine...
24,2446,amaral,277895,7364480,"Amaral is a Spanish group, from the city of Za..."
25,1755,roxette,1918124,41302203,Roxette is a Swedish pop rock duo originally c...
26,180,abba,4451571,195948345,ABBA were a Swedish pop group formed in Stockh...
27,98,evanescence,4571527,221737611,Evanescence is a rock band founded in Little R...
28,10977,paramore,5700388,594911740,Paramore is an American rock band formed in Fr...
29,1434,la oreja de van gogh,665598,19877493,La Oreja de Van Gogh (English: Van Gogh's Ear)...
30,11289472,rauw alejandro,1137364,94730081,"Raúl Alejandro Ocasio Ruiz, known professional..."
31,9219,disney,489952,13080632,'Disney' collectively refers to the soundtrack...
32,246791,drake,6791476,1214671472,"Aubrey ""Drake"" Graham (born October 24, 1986) ..."
33,5904266,nathan dawe,378102,4132779,Nathan Dawe is an English DJ and producer. He ...
34,11,the rolling stones,5863136,276584202,The Rolling Stones are an English rock band fo...
35,4649104,tainy,825531,39138442,"Marcos Efraín Masís Fernández (San Juan, Augus..."
36,7358224,cheat codes,947850,14288149,Cheat Codes are an American electronic music t...
37,12178,calvin harris,5077758,213244146,"Adam Richard Wiles, known professionally as Ca..."
38,407188,swedish house mafia,2757650,55429085,Swedish House Mafia is a house music supergrou...
39,4495513,travis scott,3374822,692040026,"Jacques Webster (born April 30, 1992), better ..."
40,3098,george michael,3287202,58784566,George Michael (born Georgios Kyriacos Panayio...
41,380955,prince royce,765391,14922103,Geoffrey Royce Rojas was born and raised in th...
42,6396188,anne-marie,1212835,20997777,"Anne-Marie Nicholson, born in Essex, England, ..."
43,12382106,israel b,45814,1119878,Israel B -antes conocido como Markés– represen...
44,413,elton john,5278043,165715418,Sir Elton Hercules John (born Reginald Kenneth...
45,7961888,anuel aa,628709,36504893,"Emmanuel Gazmey Santiago, known professionally..."
46,210977,gesaffelstein,1580518,28426706,French DJ and electronic musician Mike Lévy pr...
47,4390053,anitta,1247598,169759541,"Larissa de Macedo Machado, known professionall..."
48,1446,paul mccartney,3322246,88901269,Sir James Paul McCartney (born 18 June 1942) i...
49,207559207,altégo,195480,1072198,Altégo is a London-based DJ and producer duo c...
50,7543848,post malone,3588720,337391501,"Austin Richard Post, known professionally as P..."
51,554792,rosalía,1891971,207806245,"Rosalia Vila Tobella, known mononymously as RO..."
52,165930,future,3261896,470281047,Nayvadius DeMun Cash (born Nayvadius DeMun Wil...
53,9761322,zayn,2297089,123262020,Zayn Malik is a multi-talented English singer-...
54,556,howard shore,1360541,61969619,"Howard Leslie Shore (born October 18, 1946) is..."
55,4968870,metro boomin,2522903,249333038,"Leland Tyler Wayne, better known by his stage ..."
56,1672366,alizzz,113282,2577414,"Cristian Quirante, professionally known as Ali..."
57,7343,carlos vives,647697,8643706,Before he graduated from Jorge Tadeo Lozano's ...
58,3968561,martin garrix,2117822,52689272,"Martijn Gerard Garritsen, born on May 14, 1996..."
59,9999412,lao ra,49594,269676,"Meet Lao Ra, the Colombian singer who uses her..."
60,12487862,bizarrap,941397,46578297,"Gonzalo Julián Conde, known artistically as Bi..."
61,8631,harold faltermeyer,445429,3388131,Hans Hugo Harold Faltermeyer (born 5 October 1...
62,9759672,cnco,513024,9685279,CNCO is a Latin American pop boy band formed i...
63,1562681,ariana grande,4538435,1139517737,"Ariana Grande-Butera, better known professiona..."
64,58568762,camilo,377413,7627312,Camilo Echeverri was the winner of XS Factor 2...
65,79181242,ciudad jara,10094,258021,"<a href=""https://www.last.fm/music/Ciudad+Jar..."
66,7457468,sen senra,166024,7097946,"Christian Senra, conocido artísticamente como ..."
67,75332,jackson 5,699203,7254412,Jackson 5 (also spelled Jackson Five or Jackso...
68,5828,dj khaled,2913653,62726572,"Khaled Mohammed Khaled, known professionally a..."
69,67972932,eddie benjamin,130520,891694,Eddie Benjamin is an Australian singer-songwri...
70,6397900,omar montes,117226,1989098,Omar Ismael Montes Moreno es un cantante y per...
71,1020109,black eyed peas,5794313,156514843,Black Eyed Peas is an American hip hop/pop gro...
72,7201102,grupo frontera,508897,13524298,Grupo Frontera is a regional Mexican band from...
73,712271,pablo alboran,59579,1348414,"<a href=""https://www.last.fm/music/+noredirec..."
74,98840272,music room 29,720,1821,"<a href=""https://www.last.fm/music/Music+Room..."
75,2896,david arnold,399890,7038266,David G. Arnold (born 23 January 1962) is an E...
76,5080,various artists,394823,3784611,Warning! Deleting this artist may remove other...
78,5835993,vianney,106080,1519207,Vianney Bureau better known by the mononym Via...
79,4860761,j balvin,1882347,66384680,"José Álvaro Osorio Balvin (born May 7, 1985), ..."
80,127322,love of lesbian,177074,11481711,Love of Lesbian is a Spanish indie pop/indie r...
81,12170972,john summit,647050,16922758,"Hailing from a city steeped in house culture, ..."
82,7072729,blue ivy,158102,1201495,"Blue Ivy Carter (born January 7, 2012) is an A..."
83,4104927,the chainsmokers,2871945,91318510,A production duo featuring Andrew Taggart and ...
84,4962,michael giacchino,1224507,31198113,"Michael Giacchino (born October 10, 1967) is a..."
85,213208547,kingston sound system,7975,17006,"<a href=""https://www.last.fm/music/Kingston+S..."
86,3922661,mora,456653,41110142,There are at least two artists with the name M...
87,230,kanye west,8002487,1564849576,"Ye, born Kanye Omari West on June 8, 1977, is ..."
88,359,nate dogg,537679,4871258,"Nathaniel Dwayne Hale (born August 19, 1969 in..."
89,8376040,dellafuente,137313,5808485,"Artista, que no rapero, under-underground gran..."
90,3265001,galantis,1619411,29580425,Originally a duo featuring Christian Karlsson ...
91,4474,estopa,310397,9031930,Estopa is a pop/flamenco duo founded in 1999 b...
92,8706544,dua lipa,3324616,324037762,Dua Lipa (born 22 August 1995) is an English s...
93,9236850,camila cabello,2454463,131306812,"Karla Camila Cabello Estrabao (born March 3, 1..."
94,141992442,pg roxette,16381,141574,"Per Gessle of Roxette <a href=""https://www.las..."
95,310260,stromae,2056407,61681804,Paul Van Haver (pronounced : pɔl vɑn ɦɑvər) (b...
96,108420982,various artists,394823,3784611,Warning! Deleting this artist may remove other...
98,4088,tony bennett,1767351,18298054,"Anthony Dominick Benedetto, known professional..."
99,5531258,sza,3539327,595487473,"Solána Imani Rowe, known professionally as SZA..."
100,4347,jorge drexler,331768,12670813,"Jorge Drexler (n. Montevideo; September 21, 19..."
101,4331004,zara larsson,2410667,94088460,Zara Maria Larsson (born 16 December 1997) is ...
102,5297021,karol g,1471238,77890816,"Carolina Giraldo Navarro, professionally known..."
103,4479,alejandro sanz,703192,15538581,"Alejandro Sanz, born Alejandro Sánchez Pizarro..."

# CREACION DE BASE DE DATOS

In [23]:
def conectar_mysql(host="127.0.0.1", user="root", password=password_sql, database=None):
    try:
        cnx = mysql.connector.connect(
            host=host,
            user=user,
            password=password,
            database=database        # si no le pasas base de datos, se conecta al servidor solo
        )
        print("Conexión exitosa")
        return cnx                      # con este return guarda la conexion y puedo usar esta conexion despues 
    except Error as e:
        print(f"Error al conectar: {e}")

In [24]:
conexion = conectar_mysql()

Conexión exitosa

In [49]:
nombre_bd = "proyecto_music_stream_team1"

In [50]:
# 
def crear_basededatos(nombre_bd):
   
    try:
        # 
        with conexion.cursor() as cursor:
            query = f"CREATE DATABASE IF NOT EXISTS {nombre_bd}"
            # 
            cursor.execute(query)
            print ("Query exitosa")
 
    # 
    except Error as e:
        print (f"Error creando base de datos: {e}")

In [89]:
crear_basededatos(nombre_bd)

Query exitosa

In [47]:
def borrar_base_datos(db_name):
    cursor = None
    try:
        with conexion.cursor() as cursor:
            cursor.execute(f"DROP DATABASE IF EXISTS {db_name}")
            print(f"Base de datos {db_name} eliminada correctamente")
    except Error as e:
        print(f"Error al eliminar la base de datos: {e}")

In [88]:
borrar_base_datos(nombre_bd)

Base de datos proyecto_music_stream_team1 eliminada correctamente

In [52]:
# para crear tablas
def crear_tablas_genericas(nombre_bd, nombre_tabla, tabla_esquema):
   
    try:
        # 
        with conexion.cursor() as cursor:
            cursor.execute(f"USE {nombre_bd};")
            # 
            query = f''' CREATE TABLE IF NOT EXISTS {nombre_tabla} ({tabla_esquema});'''
            #
            cursor.execute(query)
            print ("Query creación exitosa")
   
    #
    except Error as e:
        print (f"Error creando tabla: {e}")

In [53]:
tabla_artista = 'artista'
tabla_genero_musical = 'genero_musical'
tabla_canciones = 'canciones'
tabla_album = 'album'

In [54]:
esquema_artista = '''id_artista INT PRIMARY KEY,
   nombre VARCHAR(30) NOT NULL,
   oyentes INT,
   reproducciones BIGINT,
   biografia VARCHAR(1000) NOT NULL,
   genero VARCHAR(10),
   artista_principal BOOLEAN
   '''

In [55]:
esquema_genero_musical = '''id_genero INT PRIMARY KEY, 
nombre VARCHAR(40)'''

In [57]:
esquema_canciones = '''id_cancion BIGINT PRIMARY KEY,
id_artista INT NOT NULL,
id_album BIGINT NOT NULL,
titulo VARCHAR(200) NOT NULL,
duracion INT,
ranking_lista INT,
colaboraciones BOOLEAN,
FOREIGN KEY (id_artista)
   REFERENCES artista(id_artista),
FOREIGN KEY (id_album)
   REFERENCES album(id_album)
'''

In [58]:
esquema_album = ''' id_album BIGINT PRIMARY KEY,
id_artista INT,
id_genero INT,
titulo VARCHAR(200) NOT NULL,
numero_canciones INT,
fecha_lanzamiento DATE,
FOREIGN KEY (id_genero)
   REFERENCES genero_musical(id_genero),
FOREIGN KEY (id_artista)
   REFERENCES artista(id_artista)
'''

In [90]:
crear_tablas_genericas(nombre_bd, tabla_genero_musical, esquema_genero_musical)

Query creación exitosa

In [91]:
crear_tablas_genericas(nombre_bd,tabla_artista, esquema_artista)

Query creación exitosa

In [92]:
crear_tablas_genericas(nombre_bd,tabla_album, esquema_album)

Query creación exitosa

In [93]:
crear_tablas_genericas(nombre_bd,tabla_canciones, esquema_canciones)

Query creación exitosa

# INSERCIÓN EN MYSQL

In [94]:
cursor = conexion.cursor()

In [95]:
cursor.execute(f'''USE {nombre_bd};''')
query_insert = f'''INSERT INTO {tabla_artista} (id_artista, nombre, oyentes, reproducciones, biografia)
VALUES (%s, %s, %s, %s, %s)'''
df_limpio = df_combinado_artistas.replace({np.nan: None, 'nan': None, 'Nan': None}) #para quitar informacion vacia
df_limpio = df_limpio[['id_artista','nombre','oyentes','reproducciones','biografia']]
df_valores = df_limpio.values.tolist()
cursor.executemany(query_insert, df_valores)
conexion.commit()

In [96]:
cursor.execute(f'''USE {nombre_bd};''')
query_insert = f'''INSERT INTO {tabla_genero_musical} (id_genero, nombre)
VALUES (%s, %s)'''
df_limpio = df_genero_final.replace({np.nan: None, 'nan': None, 'Nan': None}) 
df_limpio = df_limpio[['id','name']]
df_valores = df_limpio.values.tolist()
cursor.executemany(query_insert, df_valores)
conexion.commit()

In [97]:
set(df_albumes["id_artista"]) - set(df_combinado_artistas["id_artista"])

set()

In [98]:
cursor.execute(f'''USE {nombre_bd};''')
query_insert = f'''INSERT INTO {tabla_album} (id_album, id_artista, id_genero, titulo, numero_canciones, fecha_lanzamiento)
VALUES (%s, %s, %s, %s, %s, %s)'''
df_limpio = df_albumes.replace({np.nan: None, 'nan': None, 'Nan': None}) 
df_limpio = df_limpio[['id_album', 'id_artista', 'id_genre', 'titulo', 'n_canciones', 'fecha_lanzamiento']]
df_valores = df_limpio.values.tolist()
cursor.executemany(query_insert, df_valores)
conexion.commit()

In [99]:
cursor.execute(f'''USE {nombre_bd};''')
query_insert = f'''INSERT INTO {tabla_canciones} (id_cancion, id_artista, id_album, titulo, duracion, ranking_lista, colaboraciones)
VALUES (%s, %s, %s, %s, %s, %s, %s)'''

df_limpio = df_canciones.replace({np.nan: None, 'nan': None, 'Nan': None}) #para quitar informacion vacia
df_limpio = df_limpio[['id_cancion', 'id_artista', 'id_album', 'title', 'duration', 'rank', 'contributors_bool']]
df_valores = df_limpio.values.tolist()
cursor.executemany(query_insert, df_valores)
conexion.commit()

In [100]:
diccionario_genero = {"Taylor Swift": "femenino",
                       "Shakira": "femenino", 
                       "Beyoncé": "femenino", 
                       "Rihanna": "femenino", 
                       "Lady Gaga": "femenino", 
                       "Adele": "femenino", 
                       "Madonna": "femenino", 
                       "Britney Spears": "femenino", 
                       "BLACKPINK": "femenino", 
                       "Little Mix":"femenino", 
                       "Coldplay": "masculino",     
                       "Bad Bunny": "masculino",     
                       "Queen": "masculino",     
                       "Eminem": "masculino",     
                       "The Weeknd": "masculino",     
                       "Ed Sheeran": "masculino",     
                       "Metallica": "masculino",     
                       "C. Tangana": "masculino",     
                       "Michael Jackson": "masculino",    
                        "Shawn Mendes": "masculino",     
                        "The Cranberries": "mixto",     
                        "Garbage": "mixto",     
                        "Blondie": "mixto",     
                        "Pretenders": "mixto",     
                        "Amaral": "mixto",     
                        "Roxette": "mixto",     
                        "ABBA": "mixto",     
                        "Evanescence": "mixto",    
                        "Paramore": "mixto", 
                        "La Oreja de Van Gogh": "mixto" }

In [101]:
cursor.execute(f'''USE {nombre_bd};''')
for nombre, genero in diccionario_genero.items(): 
    cursor.execute(f'''UPDATE {tabla_artista} SET genero = %s WHERE nombre = %s''', (genero, nombre))
conexion.commit()

In [103]:
cursor.execute(f'''UPDATE {tabla_artista} SET artista_principal = TRUE WHERE id_artista IN ({','.join(['%s']*len(id_artistas))})''', id_artistas)
cursor.execute(f'''UPDATE {tabla_artista} SET artista_principal = FALSE WHERE id_artista NOT IN ({','.join(['%s']*len(id_artistas))})''', id_artistas)
conexion.commit()

# ANALISIS Y CONSULTAS DE BASE DE DATOS

¿Suena igual para todos? Análisis de la presencia y popularidad femenina en las plataformas de streaming musical
¿Las artistas femeninas tienen la misma representación y éxito que los artistas masculinos en la música digital?

1. ¿Cuál es la media de oyentes y reproducciones de las artistas femeninas frente a los masculinos?
2. Eficiencia por canción: Si dividimos reproducciones entre el número total de canciones, ¿quién obtiene más "rendimiento" por cada tema lanzado?
3. El Techo del Ranking: ¿Cuál es la posición media en ranking_lista para las mujeres frente a los hombres?
4. Presencia en el Top: ¿Qué porcentaje de artistas en el "Top 10" (según ranking_lista) son mujeres?
5. El fenómeno de la colaboración: Según la columna colaboraciones de la tabla canciones, ¿quién colabora más? ¿Las mujeres suelen aparecer más en canciones con colaboraciones que en solitario?
6. Densidad de los álbumes: ¿Quién saca álbumes más largos (más número canciones)?
7. Frecuencia de lanzamiento: Usando fecha_lanzamiento, ¿cuál es el tiempo medio que pasa una mujer entre álbum y álbum frente a los hombres?
8. Géneros "Generizados": ¿En qué estilos musicales (nombre de la tabla genero_musical) hay una presencia nula o mínima de mujeres?

In [ ]:
# 1. ¿Cuál es la media de oyentes y reproducciones de las artistas femeninas frente a los masculinos?